### ISSUE TITLE
Expose the executable bit into a HTTP header

### ISSUE THREAD

**Issue by zimbatm** [numtide/nar-serve#2]
The NAR archive doesn't store any file attributes except the file type, and whenever the file is an executable.

It would be nice to expose whenever a file is executable in a HTTP header.

Eg:

```
X-Nar-Executable: true
```
?

**Comment by stv0g** [comment]
I've implemented a header named `NAR-Executable`.

I decided against the `X-` prefix as its discouraged since [RFC6648](https://datatracker.ietf.org/doc/html/rfc6648).
